name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Npm cache clean
      run: npm cache clean --force
    
    - name: Install Dependencies
      run: npm ci
      timeout-minutes: 10
      
    - run: npm run build --if-present
    
    - name: Go to project directory
      run: cd /home/ubuntu/actions-runner/_work/imageOptimizer/imageOptimizer
    
    - name: Restart pm2 process
      run: pm2 restart 0
    
